# Generated by Django 3.2.5 on 2021-08-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0003_bowling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='run',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
