# Generated by Django 3.2.5 on 2021-08-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0004_alter_batting_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowling',
            name='overs',
            field=models.FloatField(blank=True, default=''),
        ),
    ]
