# Generated by Django 3.2.5 on 2021-08-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0005_alter_bowling_overs'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='team1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='matches',
            name='team2',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
