# Generated by Django 3.2.5 on 2021-08-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0006_auto_20210812_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team2',
        ),
    ]
