# Generated by Django 3.2.5 on 2021-08-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0007_auto_20210812_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='cric.country'),
        ),
        migrations.AddField(
            model_name='matches',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='cric.country'),
        ),
    ]
