# Generated by Django 3.2.5 on 2021-08-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0008_auto_20210812_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='batting',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='cric.country'),
        ),
        migrations.AddField(
            model_name='batting',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='cric.country'),
        ),
        migrations.AddField(
            model_name='bowling',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t1', to='cric.country'),
        ),
        migrations.AddField(
            model_name='bowling',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t2', to='cric.country'),
        ),
    ]
