# Generated by Django 3.2.5 on 2021-08-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cric', '0009_auto_20210812_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batting',
            old_name='team1',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='bowling',
            old_name='team1',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='batting',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='bowling',
            name='team2',
        ),
    ]
